[package]
name = "gcl-ui"
description = "Slint desktop UI for GRID Craft Launcher"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "grid-craft-launcher"
path = "src/main.rs"

[dependencies]
gcl-core.workspace = true
